# Generated by Django 3.1.4 on 2020-12-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_sqlite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='work_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='工作编号'),
        ),
    ]
